# Generated by Django 5.1.5 on 2025-05-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_tw", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="sourceCode",
            field=models.TextField(blank=True, null=True),
        ),
    ]
