# Generated by Django 5.1.5 on 2025-02-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_tw", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="name",
            field=models.CharField(default="Untitled Project", max_length=100),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
