# Generated by Django 5.2.1 on 2025-06-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_tw", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="link",
            field=models.TextField(blank=True, null=True),
        ),
    ]
