# Generated by Django 5.1.7 on 2025-03-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_tw', '0002_alter_project_image_alter_project_technology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='../static/photos')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
