# Generated by Django 5.1.7 on 2025-03-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_tw', '0003_image_remove_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(to='portfolio_tw.image'),
        ),
    ]
