# Generated by Django 5.1.7 on 2025-03-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_tw', '0005_remove_project_images_remove_project_technology_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='../static/photos'),
        ),
    ]
